### ISSUE TITLE
"Unexpected Error" During Initial Setup

### ISSUE THREAD

**Issue by jmengit** [MizterB/homeassistant-infinitude-beyond#1]
Getting "Unexpected Error" during initial setup of the integration (entered IP and port, pressed submit) - 

```
Traceback (most recent call last):
  File "/config/custom_components/infinitude_beyond/config_flow.py", line 64, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/infinitude_beyond/config_flow.py", line 43, in validate_input
    await infinitude.connect()
  File "/config/custom_components/infinitude_beyond/infinitude/api.py", line 177, in connect
    self.zones[zone_id]._update_activities()
  File "/config/custom_components/infinitude_beyond/infinitude/api.py", line 508, in _update_activities
    self._activity_scheduled = activity_scheduled
                               ^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'activity_scheduled' where it is not associated with a value
```

**Comment by jmengit** [comment]
Confirmed this was fixed. Closing the issue
