### ISSUE TITLE
Hostnames with a dash don't work

### ISSUE THREAD

**Issue by brettonw** [MizterB/homeassistant-infinitude-beyond#17]
If I run my infinitude server on a machine with a dash in the name, like "rpi-inf.local", Home assistant will connect, but then mysteriously report "Unexpected error fetching rpi-inf.local:3002 data"

The log looks like this:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/infinitude_beyond/__init__.py", line 81, in _async_update_data
    await self.infinitude.update()
  File "/config/custom_components/infinitude_beyond/infinitude/api.py", line 206, in update
    status, config, energy = await asyncio.gather(
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/infinitude_beyond/infinitude/api.py", line 152, in _fetch_config
    data = resp.get("data", {})
           ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

Infinitude seems to be connected just fine.

**Comment by brettonw** [comment]
Looking at the Infinitude source itself... It *looks like* dumb luck on my part - host names with dashes in them or "infinitude", "carrier", etc. are all bad inside the Infinitude server. Changing the host name to "inf" worked just fine.
