### ISSUE TITLE
New error in logs - "Preheating" related (?)

### ISSUE THREAD

**Issue by greggitter** [MizterB/homeassistant-infinitude-beyond#35]
Just checking my logs this morning for something else and noticed this is a repeating error message once about every 15 minutes.  There are no automations active regarding HVAC...and this appears to be related to the preheating period of time prior to "Wake".  Not sure this is even related to infinitude...?  If not is it worth reporting elsewhere?  Thx.

```
2024-12-02 06:28:58.765 ERROR (MainThread) [homeassistant.helpers.event] Error while dispatching event for climate.zone_1_thermostat to <Job track state_changed event ['climate.zone_1_thermostat'] HassJobType.Callback <bound method HomeAccessory.async_update_event_state_callback of <accessory display_name='ZONE 1 Thermostat' services=['AccessoryInformation', 'Thermostat', 'Fanv2']>>>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 356, in _async_dispatch_entity_id_event
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 949, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/components/homekit/accessories.py", line 514, in async_update_event_state_callback
    self.async_update_state_callback(new_state)
  File "/usr/src/homeassistant/homeassistant/components/homekit/accessories.py", line 538, in async_update_state_callback
    self.async_update_state(new_state)
  File "/usr/src/homeassistant/homeassistant/components/homekit/type_thermostats.py", line 692, in async_update_state
    self._async_update_fan_state(new_state)
  File "/usr/src/homeassistant/homeassistant/components/homekit/type_thermostats.py", line 722, in _async_update_fan_state
    HC_HASS_TO_HOMEKIT_FAN_STATE[hvac_action]
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: <HVACAction.PREHEATING: 'preheating'>
```

**Comment by MizterB** [comment]
I see this occasionally as well - appears to be due to HomeKit not recognizing the 'preheating' state.  Not sure there is anything I can do here, better to report back to HA Core.
