### ISSUE TITLE
Thermostat adjustments result in error messages

### ISSUE THREAD

**Issue by GizmoGoody** [MizterB/homeassistant-infinitude-beyond#7]
I'm trying to change preset modes and manually adjust the set point. 

Both give me this toast message...

Failed to call service climate/set_preset_mode. unexpected character: line 1 column 1 (char 0)

...and this in the HA log...

This error originated from a custom integration.

Logger: custom_components.infinitude_beyond.infinitude.api
Source: custom_components/infinitude_beyond/infinitude/api.py:620
integration: Infinitude Beyond (documentation)
First occurred: May 23, 2024 at 5:59:28 AM (2355 occurrences)
Last logged: 2:08:01 PM

'None' is an unknown HVACAction

It seems like the changes eventually take effect.

**Comment by MizterB** [comment]
Please retest in 2024.6.0 and report back

**Comment by electricessence** [comment]
Getting same issue.  I'll update to 2024.6.0 at some point and report back.

**Comment by mrcushing** [comment]
I'm on 2024.6.0 and still receiving this error.

**Comment by electricessence** [comment]
I updated and the issue went away.
I updated both docker images.

**Comment by GitHubGoody** [comment]
I just test on 2024.6.0 and still getting an error.

![image](https://github.com/MizterB/homeassistant-infinitude-beyond/assets/46235745/d447c53d-4d70-4671-b38f-914e2d2ce14c)

**Comment by kswa1987** [comment]
Seeing this same error. The failed to call service error just above. Strangely, everything works despite the error!

**Comment by MizterB** [comment]
I'm flying blind as I don't get the same issue on my end.  However, I made some logging improvements for the next release, which should hopefully provide more insight.

**Comment by MizterB** [comment]
Please upgrade to 2024.8.0, enable debug logging, and share the log output when the service call fails.

**Comment by mrcushing** [comment]
> Please upgrade to 2024.8.0, enable debug logging, and share the log output when the service call fails.

Here you go (with my IP deleted out in two spots):

2024-08-19 13:44:32.091 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139776200999264] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2763, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2806, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 999, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1071, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 951, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/config/custom_components/infinitude_beyond/climate.py", line 162, in async_set_temperature
    await self.zone.set_temperature(temperature=temperature)
  File "/config/custom_components/infinitude_beyond/infinitude/api.py", line 839, in set_temperature
    await self.set_hold_mode(mode=HoldMode.UNTIL, activity=Activity.MANUAL)
  File "/config/custom_components/infinitude_beyond/infinitude/api.py", line 796, in set_hold_mode
    await self._infinitude._post(endpoint, data)
  File "/config/custom_components/infinitude_beyond/infinitude/api.py", line 91, in _post
    resp_json: dict = await resp.json(content_type=None)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 80, in json
    return await super().json(*args, loads=loads, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1215, in json
    return loads(stripped.decode(encoding))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 44, in json_loads
    return orjson.loads(__obj)  # type:ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
orjson.JSONDecodeError: unexpected character: line 1 column 1 (char 0)
2024-08-19 13:44:41.043 DEBUG (MainThread) [custom_components.infinitude_beyond.infinitude.api] Updating from Infinitude
2024-08-19 13:44:41.203 DEBUG (MainThread) [custom_components.infinitude_beyond.infinitude.api] Config changed: {'zones/zone[1]/hold': ('off', 'on'), 'zones/zone[1]/activities/activity[4]/clsp': ('68.0', '78.0'), 'zones/zone[1]/activities/activity[4]/htsp': ('68.0', '78.0'), 'zones/zone[1]/holdActivity': ({}, 'manual'), 'zones/zone[1]/otmr': ({}, '17:30')}
2024-08-19 13:44:41.206 DEBUG (MainThread) [custom_components.infinitude_beyond] Finished fetching [DELETED OUT IP]:3000 data in 0.163 seconds (success: True)
2024-08-19 13:44:56.042 DEBUG (MainThread) [custom_components.infinitude_beyond.infinitude.api] Updating from Infinitude
2024-08-19 13:44:56.201 DEBUG (MainThread) [custom_components.infinitude_beyond.infinitude.api] Status changed: {'localTime': ('2024-08-19T13:43:23-07:00', '2024-08-19T13:43:58-07:01'), 'zones/zone[1]/clsp': ('76.0', '78.0'), 'zones/zone[1]/hold': ('off', 'on'), 'zones/zone[1]/currentActivity': ('away', 'manual'), 'zones/zone[1]/otmr': ({}, '17:30'), 'zones/zone[1]/htsp': ('66.0', '78.0')}
2024-08-19 13:44:56.210 DEBUG (MainThread) [custom_components.infinitude_beyond] Finished fetching [DELETED OUT IP]:3000 data in 0.168 seconds (success: True)

**Comment by MizterB** [comment]
@mrcushing are you able to send some of the debug output from just before the exception is raised?  That should provide the HTTP request & response that triggered it, per this code...

```python
    async def _post(self, endpoint: str, data: dict, **kwargs) -> dict:
        """Make a POST request to Infinitude."""
        url = f"{self.url}{endpoint}"
        try:
            _LOGGER.debug("POST %s with %s and %s", url, data, kwargs)
            async with self._session.post(url, data=data, **kwargs) as resp:
                _LOGGER.debug(
                    "POST RESPONSE from %s with %s and %s is: %s",
                    url,
                    data,
                    kwargs,
                    await resp.text(),
                )
                resp.raise_for_status()
                resp_json: dict = await resp.json(content_type=None)
                return resp_json
        except ClientError as e:
            _LOGGER.error(e)
```

**Comment by mrcushing** [comment]
Here's the relevant portion of the log, I think- see attached.
[home-assistant_infinitude_beyond_2024-08-19T19-45-02.183Z.log](https://github.com/user-attachments/files/16667736/home-assistant_infinitude_beyond_2024-08-19T19-45-02.183Z.log)

**Comment by MizterB** [comment]
This issue is likely affecting users who are not running the latest version of Infinitude, and are encountering this issue:
https://github.com/nebulous/infinitude/issues/185

Please update to the latest and confirm that the errors no longer occur.

**Comment by GizmoGoody** [comment]
> This issue is likely affecting users who are not running the latest version of Infinitude, and are encountering this issue: [nebulous/infinitude#185](https://github.com/nebulous/infinitude/issues/185)
> 
> Please update to the latest and confirm that the errors no longer occur.

I have all three of the entries in my Portainer stack set to `image: nebulous/infinitude:latest`. Do you know if that should still pull the latest version or do I need to set it to :master? When I dig into one of the child containers, I see a field with a key labeled com.docker.compose.version with a value of 2.10.2. Is that the Infinitude version?

Either way, I'm still getting the errors on 2024.8.3.

**Comment by MizterB** [comment]
@GitHubGoody that should pick up the latest.  However, you need to rebuild the containers.  If you use docker compose, something like this should work - not sure how to achieve the same in Portainer, I don't use it.

```bash
docker compose down
docker compose pull
docker compose up -d
```

**Comment by GizmoGoody** [comment]
@MizterB Thanks. This whole time I thought it was keeping itself updated. 🤦🏻‍♂️

It was easy enough to just update the stack which includes an option to "Re-pull image and redeploy." But, I also figured out how to configure the stack for GitOps updates.

Now that key indicates 2.24.6 and the error no longer pops up.

Thanks again!
